name: down paper

on:
  schedule:
    # 定期运行触发器，这里设置为每天UTC时间的17点，对应北京时间次日凌晨1点
    - cron: '0 17 * * *'
  # 也允许手动触发这个工作流
#  workflow_dispatch:
  #推送时触发
  push:
    branches: [ main ]

jobs:
  build:
    # 工作流中的单个任务，这里只有一个名为“build”的任务
    runs-on: ubuntu-latest
    # 运行任务的服务器环境，这里使用最新的Ubuntu

    strategy:
      matrix:
        python-version: [ 3.11 ]
        # 定义一个策略，这里使用Python 3.11版本

    steps:
    - uses: actions/checkout@v2
      with:
        # todo:设置token用于推送权限
        token: ${{ secrets.TMP_PUSH_TOKEN }}
      # 使用GitHub Actions的checkout动作来检出仓库代码，并提供一个token用于后续的推送操作

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      # 设置Python环境，使用matrix中定义的版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Run tests
      run: |
        python -m unittest DailyDownload.py
      # 运行单元测试，调用unittest模块来执行Paper_metadata_download.py脚本

    - name: Commit changes
      run: |
        git config --global user.name "yanivsun"
        git config --global user.email "1109812755@qq.com"
#        git pull origin main

        git add .
        git commit -m "每日论文推送"
        git push
#        if [ -n "$(git diff origin/main)" ]; then
#          echo "有新的更改，准备提交..."
#          git add .
#          git commit -m "每日论文推送"
#          git push
#        else
#          echo "没有新的更改，跳过提交。"
#        fi
#        git add .
#        git commit -m "每日论文推送"
      # 提交更改，设置Git的用户信息，将所有更改添加到暂存区，并提交一个带有消息的提交

#    - name: Push changes
#      run: |
#        git push
